feat: 로그인 페이지 레이아웃 구성
Pinkippo/Flutter_Balance-Game_Client_V2 pull request #2
Opened 2024-07-01 04:43 UTC by SuuuHyeon

2024-07-01 11:44 UTC, Pinkippo reviewed
전체적으로 코드 분리도 잘 되어있고 깔끔하지만 Getx를 전혀 사용하고있지 않습니다.

2024-07-01 11:55 UTC, Pinkippo requested changes
수정부탁드립니다

2024-07-02 05:45 UTC, SuuuHyeon commented
상태관리 적용해봤습니다. 확인 부탁드려요.

2024-07-02 07:18 UTC, Pinkippo reviewed
@SuuuHyeon 크게 문제점은 보이지 않지만 수정해야할 부분이 보여
퇴근 후 작업하여 반영하도록 하겠습니다.

2024-07-02 10:38 UTC, Pinkippo approved these changes
@SuuuHyeon 코드 수정 완료했습니다.
통과하겠습니다. 확인하고 병합하세요

2024-07-02 16:26 UTC, merged